# Generated by Django 2.0.1 on 2018-01-18 18:07

from django.db import migrations


def create_subjects(apps, schema_editor):
    Subject = apps.get_model('classroom', 'Subject')
    Subject.objects.create(name='BASES DE DONNÉES RELATIONNELLES', color='#343a40')
    Subject.objects.create(name='CONCEPTION ET ANALYSE DES ALGORITHMES', color='#007bff')
    Subject.objects.create(name='TRAITEMENT DE SIGNA', color='#28a745')
    Subject.objects.create(name='SYSTEMES D EXPLOITATION', color='#17a2b8')
    Subject.objects.create(name='PROGRAMMATION PYTHON', color='#ffc107')
    Subject.objects.create(name='INTRODUCTION AUX RÉSEAUX TÉLÉCOMS ET RÉSEAUX D’ENTREPRISES', color='#3F5378')
    Subject.objects.create(name=' INGÉNIERIE DES SYSTÈMES D’EXPLOITATION', color='##202A34')   
    Subject.objects.create(name='ANALYSE NUMÉRIQUE ET OPTIMISATION', color='##44D476')    

class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_subjects),
    ]
